version: '3.8'

services:
  app: 
    container_name: app
    build: ./
    ports:
      - 3000:8000
    volumes:
      - ./:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scan_my_git
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/#ports for more information.
      - '3306'
