version: '3.8'

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: ./docker/php
        ports:
            - 9000:9001
        volumes:
            - ./:/var/www/html
        depends_on:
            -   database

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=root

    nginx:
        tty: true
        container_name: nginx
        build:
            context: ./docker/nginx
        ports:
            - 3000:8080
        depends_on:
            - php-fpm
        volumes:
            - ./:/var/www/html
            - ./logs/nginx:/var/log/nginx
        

    database:
        image: 'mariadb:latest'
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: scan_my_git
        ports:
            - '3306'
